// File created by
// Lung Razvan <long1eu>
// on 19/09/2018

/**
 * <p>
 * A characteristic specifies an aspect of a system under test.
 * </p>
 * <p>
 * The characteristic stated is tested with a number of test data instances
 * generated by a generator. All runs of a characteristic's
 * {@link Characteristic#specify(Object)} method have to be valid. Invalid runs
 * have to throw an exception.
 * </p>
 *
 * @param <T>
 *            type of generated random test instances
 *
 */
abstract class Characteristic<T> {
  /**
   * Checks the characteristic's specification for a test case instance.
   *
   * @param instance
   *            for which to check the characteristic
   * @throws Throwable
   *             if the instance does not confirm to the characteristic's
   *             specification
   */
  void specify(T instance);

  /**
   * Set up operation before {@link Characteristic#specify(Object)} is
   * executed.
   */
  void setUp();

  /**
   * Clean up operation after {@link Characteristic#specify(Object)} was
   * executed.
   */
  void tearDown();

  /**
   * Unique name for this characteristic instance.
   *
   * @return name of the characteristic.
   */
  String get name;
}
